# http://www.romajidesu.com/


body_list = {
    "ankle": "あしくび",
    "arm": "うで",
    "back": "せなか",
    "beard": "ひげ",
    "blood": "ち",
    "body": "どう",
    "bone": "ほね",
    "brain": "のう",
    "cheek": "ほお",
    "chest": "むね",
    "chin": "あご",
    "ear": "みみ",
    "elbow": "ひじ",
    "eye": "ひとみ",
    "face": "めん",
    "finger": "ゆび",
    "fingers": "",
    "flesh": "",
    "foot": "あし",
    "hair": "",
    "hand": "",
    "hands": "",
    "head": "",
    "heart": "",
    "hip": "",
    "knee": "",
    "knees": "",
    "leg": "",
    "legs": "",
    "lip": "",
    "moustache": "",
    "mouth": "",
    "muscle": "",
    "nail": "",
    "neck": "",
    "nose": "",
    "shoulder": "",
    "shoulders": "",
    "skin": "",
    "stomach": "",
    "teeth": "",
    "throat": "",
    "thumb": "",
    "thumbs": "",
    "toe": "",
    "toes": "",
    "tongue": "",
    "tooth": "",
    "wrist": "",
}

word_list = {

}
